[build]
  publish = "."

# Service worker headers
[[headers]]
for = "/prxe/sw.js"
[headers.values]
  Service-Worker-Allowed = "/prxe/"
  Cache-Control = "no-store"

# Route all /prxe/* URLs to the fetch function
[[redirects]]
from = "/prxe/*"
to = "/.netlify/functions/fetch?url=:splat"
status = 200
force = true