[build]
  publish = "."           # or "public" or wherever your site build output is
  functions = "netlify/functions"

[[redirects]]
  from = "/p/*"
  to = "/.netlify/functions/proxy?url=:splat"
  status = 200
  force = true